spring:
  config:
    import:
      - "aws-secretsmanager:cafe/api-gateway"
      - "rds!cluster-cb0cfbce-010d-4b94-98dc-9bfc73234f43"


  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${username}
    password: ${password}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  jwt:
    secret: ${JWT_SECRET}
    access_expiration: 3600000 #1hour
    refresh_expiration: 2592000000 #30days

gateway:
  secret: ${GATEWAY_SECRET}